### ISSUE TITLE
Do not use static attributes for instrumentation of Enums

### ISSUE THREAD

**Issue by stro18** [kieker-monitoring/kieker-source-instrumentation#2]
**Suggested Solution**
(Example) Use
```
final long _kieker_sourceInstrumentation_tin = kieker.monitoring.core.controller.MonitoringController.getInstance().getTimeSource().getTime();
```
instead of 
```
final long _kieker_sourceInstrumentation_tin = ApplicationSessionCookieConfig._kieker_sourceInstrumentation_TIME_SOURCE.getTime();
```

**Note**
Might already be implemented and the implementation of Peass might be responsible  for the false instrumentation.

**Comment by stro18** [comment]
The error only occurred for measurement instrumentation of root cause analysis. An example enum for that error is https://github.com/apache/tomcat/blob/main/java/jakarta/persistence/PersistenceContextType.java

**Comment by stro18** [comment]
The error occurred with multiple test cases of Tomcat. This is one of the commands I executed that contains the error: 

`./peasstomcat searchcauseParameterized 37bc60c9efed390f662afe0a1d12d2ba0d91ada8 org.apache.jasper.servlet.TestJspCServletContext#testResourceJARs`

For that command the error occured in https://github.com/stro18/tomcat/blob/37bc60c9efed390f662afe0a1d12d2ba0d91ada8/java/org/apache/tomcat/JarScanType.java

**Comment by DaGeRe** [comment]
This should work since https://github.com/DaGeRe/kieker-source-instrumentation-dagere/commit/2bc48ed73dcfa52ceb75667ee373339108a1ce88, can you confirm this?

**Comment by stro18** [comment]
Can confirm that this works.
